accent = "#e0e0e0"
cursor = "#e0e0e0"
foreground = "#e0e0e0"
background = "#000000"
selection_foreground = "CellBackground"
selection_background = "CellForeground"

color0 = "#000000"
color1 = "#e19e74"
color2 = "#a5a297"
color3 = "#c6c4b0"
color4 = "#605d5b"
color5 = "#8a8575"
color6 = "#C2BBB0"
color7 = "#d0d0d0"
color8 = "#383735"
color9 = "#984b1e"
color10 = "#637380"
color11 = "#8f4445"
color12 = "#b7a798"
color13 = "#b3adad"
color14 = "#90947a"
color15 = "#ffffff"
