accent = "#605d5b"
cursor = "#a4a4a4"
foreground = "#a4a4a4"
background = "#121212"
selection_foreground = "CellBackground"
selection_background = "CellForeground"

color0 = "#121212"
color1 = "#e19e74"
color2 = "#a5a297"
color3 = "#c6c4b0"
color4 = "#605d5b"
color5 = "#8a8575"
color6 = "#C2BBB0"
color7 = "#dbd9d3"
color8 = "#383735"
color9 = "#984b1e"
color10 = "#637380"
color11 = "#8f4445"
color12 = "#b7a798"
color13 = "#b3adad"
color14 = "#90947a"
color15 = "#a4a4a4"
